### ISSUE TITLE
FastDMG Preferences window has started appearing every time I open a DMG

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/FastDMG#1]
FastDMG Preferences window has started appearing every time I open a DMG.

![screen shot 2018-07-16 at 00 57 04](https://user-images.githubusercontent.com/49612/42739658-37ac6024-8893-11e8-9387-ad637fd232bf.png)

Very odd.

High Sierra latest

**Comment by sveinbjornt** [comment]
This looks like a macOS bug since it's also happening with Platypus apps. But I just pushed a commit to FastDMG that tries to fix the issue, may be a timing issue. Does it still occur if you build the latest version? I'm abroad at the moment and haven't set up Mojave for testing.

**Comment by gingerbeardman** [comment]
Thanks for the reply.

I'm not on Mojave yet, either, just High Sierra. I'll try building the latest version tonight. 

It really made it obvious how many times I use FastDMG and Platypus apps every day.

**Comment by gingerbeardman** [comment]
@sveinbjornt your changes fix the issue — many thanks!

Will leave this open, close when you see fit.

**Comment by gingerbeardman** [comment]
This seems fixed for me on 10.13.6 (17G65) 

Also similar issue with Platypus apps has gone away.
