### ISSUE TITLE
Option to change location of mount point(s) / different locations for DMGs and sparsebundles

### ISSUE THREAD

**Issue by JayBrown** [sveinbjornt/FastDMG#5]
DMGs are usually mounted in `/Volumes`, but initially that location (like `/media`) was for detachable devices, physical storage etc. DMGs and sparsebundles are of a different kind, often ephemeral (especially DMGs), so my question is if it's possible to add an option to select an alternate location for the mount points, e.g. `/mnt` or `~/mnt` instead of `/Volumes`… maybe even have two settings, one location for DMG mount points, one for sparsebundle mount points. Can't say if FastDMG would have to create directories to use as mount points in such a location, or if macOS/hdiutil would do that automatically.

**Comment by JayBrown** [comment]
PS: though I can't say if this wouldn't actually break stuff, e.g. in-app updaters that download & silently mount DMGs for background installation. (?)

**Comment by sveinbjornt** [comment]
This is a fringe use case, in my opinion. If you want a different mount point, you can add the arguments

```
@"-mountroot",  @"/path/to/mountpoint/"
``` 

here:

https://github.com/sveinbjornt/FastDMG/blob/b24b5f55157d63c0ad071ba44faad22052f3adc1/FastDMG/FastDMGAppDelegate.m#L167

and build your own version.
