### ISSUE TITLE
Installation via `brew`

### ISSUE THREAD

**Issue by andreiborisov** [sveinbjornt/FastDMG#6]
Thank you for such an awesome little utility!

It would be nice to be able to install it via `brew`.

**Comment by davidldennison** [comment]
Definitely!

**Comment by Moulick** [comment]
I am making a PR to add this to Brew! @sveinbjornt Is there any way to get a versioned download URL for the compiled app? Or maybe add the `.app/.zip` to the GitHub Release? If the download url is un-versioned, `https://sveinbjorn.org/files/software/FastDMG.zip` brew cannot cannot ensure the sha256 checksum :(

**Comment by Moulick** [comment]
Never mind about the versioned url, the GitHub readme has un-versioned but the homepage _has_ versioned :)

**Comment by Moulick** [comment]
PR has been merged, now available as `brew install fastdmg`.
